package.json, pnpm-lock.yaml, src/external/mongo/db.ts, src/external/mongo/indexes.ts, src/server/middleware/auth.test.ts, src/server/middleware/auth.ts, src/server/middleware/update-last-seen.ts, src/server/router/api/v1/auth/auth.ts, src/server/router/api/v1/auth/router.ts, src/server/router/api/v1/import/router.ts, src/server/router/api/v1/users/_userID/middleware.ts, src/server/router/api/v1/users/_userID/router.ts, src/server/router/api/v1/users/_userID/settings/router.test.ts, src/server/router/api/v1/users/_userID/settings/router.ts, src/test-utils/mock-db/user-settings.json, src/test-utils/resets.ts, src/utils/types.ts, src/utils/user.ts
=> Add global user settings

src/lib/score-import/import-types/ir/fervidex-static/parser.ts, src/lib/score-import/import-types/ir/fervidex/converter.test.ts, src/lib/score-import/import-types/ir/fervidex/converter.ts, src/lib/score-import/import-types/ir/fervidex/parser.ts, src/lib/score-import/import-types/ir/fervidex/types.ts
=> Support fervidex DP Randoms

src/lib/score-import/import-types/ir/beatoraja/converter.ts
=> Reject CN/HCN mode scores.

.gitignore, package.json, pnpm-lock.yaml, scripts/__KT_DATABASE_MIGRATION/user-private-info.ts, scripts/__KT_DATABASE_MIGRATION/users.ts, src/external/mongo/db.ts, src/external/mongo/indexes.ts, src/external/mongo/schemas.ts, src/lib/search/search.ts, src/server/router/api/v1/auth/auth.ts, src/server/router/api/v1/auth/router.ts, src/server/router/api/v1/games/_game/_playtype/charts/_chartID/router.test.ts, src/server/router/api/v1/users/_userID/games/_game/_playtype/showcase/router.test.ts, src/server/router/api/v1/users/_userID/settings/router.test.ts, src/server/router/api/v1/users/router.test.ts, src/server/router/api/v1/users/router.ts, src/server/router/ir/usc/router.test.ts, src/server/router/ir/usc/usc.test.ts, src/test-utils/mock-db/user-private-information.json, src/test-utils/mock-db/users.json, src/utils/user.test.ts, src/utils/user.ts
=> Fix #306 (User-private-info-should-be-moved-to-a-separate-collection)

package.json, pnpm-lock.yaml, src/external/mongo/db.ts, src/lib/setup/config.ts, src/server/router/api/v1/oauth/clients/middleware.test.ts, src/server/router/api/v1/oauth/clients/middleware.ts, src/server/router/api/v1/oauth/clients/router.test.ts, src/server/router/api/v1/oauth/clients/router.ts, src/server/router/api/v1/oauth/router.test.ts, src/server/router/api/v1/oauth/router.ts, src/server/router/api/v1/router.ts, src/server/router/api/v1/users/_userID/api-tokens/router.test.ts, src/server/router/api/v1/users/_userID/api-tokens/router.ts, src/server/router/api/v1/users/_userID/router.ts, src/test-utils/mock-db/oauth2-auth-codes.json, src/test-utils/mock-db/oauth2-clients.json, src/utils/misc.test.ts, src/utils/misc.ts, src/utils/types.ts
A lot of documentation work is now needed, and so is a lot of client work! haha. :(
=> Support OAuth2 Integration

src/lib/constants/time.ts, src/lib/invites/invites.ts, src/server/middleware/type-require.ts, src/server/router/api/v1/users/_userID/invites/router.test.ts, src/server/router/api/v1/users/_userID/invites/router.ts, src/server/router/api/v1/users/_userID/router.ts, src/test-utils/mock-db/invites.json
=> Invite Management and Invite Reading for Admins

src/server/router/ir/beatoraja/charts/convert-scores.test.ts, src/server/router/ir/beatoraja/charts/convert-scores.ts, src/server/router/ir/beatoraja/charts/router.ts
=> Optimise GET /ir/beatoraja/chart/:chartSHA256/scores

README.md, scripts/__KT_DATABASE_MIGRATION/scores/bms.ts, scripts/__KT_DATABASE_MIGRATION/scores/iidx.ts, scripts/__KT_DATABASE_MIGRATION/scores/migrate-all.ts, scripts/__KT_DATABASE_MIGRATION/scores/museca.ts, scripts/__KT_DATABASE_MIGRATION/scores/reference.ts, scripts/__KT_DATABASE_MIGRATION/scores/sdvx.ts, scripts/__KT_DATABASE_MIGRATION/sessions.ts, scripts/__KT_DATABASE_MIGRATION/state-sync/recalc-sessions.ts, scripts/__KT_DATABASE_MIGRATION/state-sync/sync-state.ts, scripts/__KT_DATABASE_MIGRATION/user-private-info.ts, scripts/__KT_DATABASE_MIGRATION/users.ts, src/server/router/api/v1/sessions/_sessionID/middleware.ts
=> Fix broken session porting script

.gitignore, scripts/quick-insert/quick-insert.ts, scripts/single-use/destroy-versionbleed-scores/destroy.ts, src/server/router/api/v1/admin/router.ts
This adds version identifiers back to tricoro, for compatibility with arcades.
=> Support IIDX back to tricoro

package.json, pnpm-lock.yaml, scripts/__KT_DATABASE_MIGRATION/user-settings.ts, scripts/__KT_DATABASE_MIGRATION/users.ts, src/server/router/api/v1/auth/auth.ts, src/server/router/api/v1/users/_userID/settings/router.ts
This lets users opt in to slightly less appropriate splash texts.
=> Add contentiousContent preference.

package.json, pnpm-lock.yaml, scripts/quick-insert/quick-insert.ts, scripts/single-use/convert-2dxtra-charts.ts, src/external/mongo/indexes.ts, src/lib/score-import/import-types/common/eamusement-iidx-csv/parser.ts, src/server/router/api/v1/games/_game/_playtype/charts/router.ts, src/utils/queries/charts.ts, src/utils/queries/stats.ts
This fixes a lot of issues with searching, as 2dxtra songs would appear with the same priorities as the real songs.
We'll need some UI overrides to handle the rest of this though.
=> Make 2dxtra difficulties normal difficulties.

package.json, pnpm-lock.yaml, src/external/mongo/db.ts, src/external/mongo/indexes.ts, src/lib/score-import/framework/user-game-stats/classes.test.ts, src/lib/score-import/framework/user-game-stats/classes.ts, src/lib/score-import/framework/user-game-stats/update-ugs.ts, src/server/router/api/v1/games/_game/_playtype/charts/_chartID/router.ts, src/server/router/api/v1/games/_game/_playtype/router.test.ts, src/server/router/api/v1/games/_game/_playtype/router.ts
=> Add class achievement APIs.

src/utils/queries/charts.ts
=> Massively optimise FindChartsOnPopularity.

src/lib/score-import/framework/user-game-stats/update-ugs.test.ts, src/server/router/api/v1/games/_game/_playtype/charts/router.test.ts, src/server/router/api/v1/games/_game/_playtype/scores/router.ts, src/server/router/api/v1/users/_userID/games/_game/_playtype/pbs/router.ts, src/server/router/ir/fervidex/router.test.ts, src/utils/queries/pbs.ts
This adds some new miscellaneous API endpoints.
=> New Misc API Endpoints.

package.json, pnpm-lock.yaml, src/lib/game-settings/create-game-settings.ts, src/lib/showcase/get-stats.test.ts, src/server/router/api/v1/users/_userID/games/_game/_playtype/showcase/router.test.ts, src/server/router/ir/beatoraja/auth.test.ts, src/test-utils/test-data/beatoraja/base.json
This PR adds support for the title, which we need for the UI.
=> Add support for gameSpecific Preferences

.github/test.conf.json5, src/lib/email/client.ts, src/lib/score-import/import-types/common/api-kai/sdvx/converter.test.ts, src/lib/setup/config.ts, src/server/router/api/v1/auth/router.ts
This PR makes TRANSPORT_OPS fully configurable from conf5.
=> Refactor TRANSPORT_OPS

package.json, pnpm-lock.yaml, scripts/clone-and-anonymise-db.ts, src/external/mongo/db.ts, src/external/mongo/indexes.ts, src/external/mongo/schemas.ts, src/lib/builtin-clients/builtin-clients.ts, src/lib/score-import/framework/goals/goals.ts, src/lib/score-import/framework/milestones/milestones.ts, src/lib/webhooks/webhooks.ts, src/main.ts, src/server/router/api/v1/clients/middleware.test.ts, src/server/router/api/v1/clients/middleware.ts, src/server/router/api/v1/clients/router.test.ts, src/server/router/api/v1/clients/router.ts, src/server/router/api/v1/oauth/router.test.ts, src/server/router/api/v1/oauth/router.ts, src/server/router/api/v1/router.ts, src/server/router/api/v1/users/_userID/api-tokens/router.ts, src/server/router/api/v1/users/_userID/integrations/kai/_kaiType/router.ts, src/test-utils/mock-db/api-clients.json, src/test-utils/mock-db/oauth2-clients.json, src/utils/class.ts, src/utils/types.ts
This change adds builtin OAuth2 Clients and a bunch more stuff.
=> Refactor OAuth2 Clients

src/lib/jobs/inline-job-runner.ts/job-runner.ts, src/server/router/api/v1/users/_userID/banner/router.ts, src/server/router/api/v1/users/_userID/pfp/router.ts
=> Allow gifs as profile pictures and banners.

src/lib/score-import/framework/score-importing/insert-score.test.ts, src/lib/score-import/framework/score-importing/insert-score.ts, src/lib/score-import/framework/score-importing/score-importing.ts
This is a small improvement to avoid any absurd race conditions in the future. This is also in preparation for #406.
Fixes #418
=> Every UserID should get their own score queue.

src/server/router/api/v1/auth/router.ts
=> fix inverted INVITE_CODE_CONFIG conditional

src/lib/score-import/framework/score-importing/score-import-main.ts, src/lib/score-import/import-types/ir/usc/converter.ts, src/lib/score-import/import-types/ir/usc/parser.ts, src/server/router/ir/usc/_playtype/types.ts, src/test-utils/test-data.ts
=> Add IR/USC combo support

src/server/middleware/prudence-validate.test.ts, src/server/middleware/request-logger.ts, src/server/router/api/v1/auth/router.test.ts, src/server/router/api/v1/auth/router.ts, src/test-utils/fake-auth.ts
=> Use ArchLinux-like !bangs for private information.

src/lib/score-import/framework/score-importing/score-import-main.ts
This doesn't really fix #461, but it reduces its severity.
=> Band-aid over partial-import failures in ImportAllIterableData.

package.json, pnpm-lock.yaml, src/lib/jobs/inline-job-runner.ts/job-runner.ts, src/lib/score-import/framework/score-import.ts, src/lib/score-import/framework/score-importing/score-import-main.ts, src/lib/score-import/framework/score-importing/score-importing.ts, src/lib/score-import/import-types/file/eamusement-sdvx-csv/converter.test.ts, src/lib/score-import/import-types/file/eamusement-sdvx-csv/parser.test.ts, src/lib/score-import/worker/queue.ts, src/lib/score-import/worker/types.ts, src/lib/score-import/worker/worker.ts, src/lib/setup/config.ts, src/main.ts, src/server/router/api/v1/clients/router.test.ts, src/server/router/api/v1/games/_game/_playtype/charts/router.ts, src/server/router/api/v1/games/_game/_playtype/router.ts, src/server/router/api/v1/import/router.test.ts, src/server/router/api/v1/imports/router.ts, src/server/router/api/v1/router.ts, src/server/router/api/v1/users/_userID/api-tokens/router.test.ts, src/server/router/ir/fervidex/router.ts, src/server/router/ir/kshook/sv3c/router.ts, src/utils/efficient-db-iterate.ts, src/utils/user.test.ts
=> Concurrencize workers.

src/server/router/api/v1/admin/router.ts
The sync-database script unsynced nyannurs's scores, we need to have a way of fixing that.
=> Add an obliterate chart endpoint.

src/lib/score-import/framework/score-importing/score-import-main.ts, src/lib/score-import/import-types/ir/fervidex-static/class-handler.ts
Fixes #480, Which is not really a bug, but a questionable interaction.
=> Always run classHandler if provided.

src/lib/score-import/import-types/ir/usc/converter.test.ts, src/lib/score-import/import-types/ir/usc/converter.ts, src/lib/score-import/import-types/ir/usc/parser.ts, src/server/router/ir/usc/_playtype/types.ts
"Support", It just maps it to a failstate.
=> Support Permissive Gauge for USC

src/server/router/ir/beatoraja/auth.ts
This fixes a bug in the beatoraja IR tests, but properly.
=> Re-Enable X-TachiIR-Version checking

package.json, src/lib/constants/version.ts, src/utils/folder.ts
Release with only one bug fix, just to test the new release flow to be honest.
- Fixes a bug where bms tables would never load or do anything.
=> Release v2.0.3

scripts/folders/folder-cache.ts
Can fast merge this -- no tests are altered.
=> Change folder-cache return code from 1 to 0

src/lib/builtin-clients/builtin-clients.ts
=> PopnHook Support

package.json, pnpm-lock.yaml, src/lib/score-import/framework/user-game-stats/rating.test.ts, src/lib/score-import/framework/user-game-stats/rating.ts, src/lib/score-import/framework/user-game-stats/update-ugs.test.ts, src/server/router/ir/usc/_playtype/usc.ts, src/test-utils/test-data.ts
=> Ratings should be nullable.

src/external/mongo/indexes.ts
=> Add various game specific indexes to optimise more "odd" chart access methods.

src/lib/score-import/framework/calculated-data/stats.test.ts, src/lib/score-import/framework/calculated-data/stats.ts
=> Fix a bug where scores between 1m and 1.05m in CHUNITHM were overvalued.

.github/test.conf.json5, package.json, pnpm-lock.yaml, src/external/mongo/indexes.ts, src/external/mongo/schemas.ts, src/lib/score-import/framework/calculated-data/calculated-data.ts, src/lib/score-import/framework/calculated-data/stats.ts, src/lib/score-import/framework/common/score-utils.ts, src/lib/score-import/framework/sessions/calculated-data.ts, src/lib/score-import/framework/user-game-stats/classes.ts, src/lib/score-import/framework/user-game-stats/rating.ts, src/lib/score-import/import-types/common/batch-manual/converter.test.ts, src/lib/score-import/import-types/common/batch-manual/converter.ts, src/lib/score-import/import-types/common/batch-manual/parser.test.ts, src/lib/score-import/import-types/common/batch-manual/parser.ts, src/server/router/ir/direct-manual/router.test.ts, src/test-utils/mock-db/charts-jubeat.json, src/test-utils/mock-db/songs-jubeat.json, src/test-utils/test-data.ts
Fixes #169
Fixes #163 
Fixes #620
=> Jubeat Support

CHANGELOG.md
Fixes #627
This commit does not affect any tests, and can skip the CI.
=> CHANGELOG.md (skip-ci)

src/lib/score-import/import-types/ir/beatoraja/parser.ts, src/server/router/ir/beatoraja/router.test.ts
=> Change ir/beatorajas client check to a graylist rather than a whitelist

src/server/router/api/v1/config/router.test.ts, src/server/router/api/v1/config/router.ts
=> Configuration information should be exposed on an API endpoint for the client.

src/external/mongo/indexes.ts, src/server/middleware/auth.test.ts, src/server/middleware/auth.ts, src/server/middleware/request-logger.ts, src/server/router/router.ts, src/server/server.ts
=> If a banned user is making a request, all requests should 403.

CHANGELOG.md, package.json, pnpm-lock.yaml, src/lib/score-import/framework/user-game-stats/rating.test.ts, src/lib/score-import/framework/user-game-stats/rating.ts
=> Support `naiveSkill` for GITADORA.

package.json, pnpm-lock.yaml, src/lib/score-import/framework/calculated-data/calculated-data.ts, src/lib/score-import/framework/calculated-data/stats.test.ts, src/lib/score-import/framework/calculated-data/stats.ts, src/lib/score-import/framework/pb/game-specific-merge.ts, src/test-utils/test-data.ts
=> Migrate to using RG-Stats for RG Stats Library.

src/lib/score-import/framework/import-locks/lock.ts, src/lib/score-import/framework/score-import.ts, src/lib/score-import/framework/score-importing/score-import-main.ts
Fixes #600
Not the best solution. Not the worst.
=> Retry imports with exponential backoff if the user already has imports ongoing.

src/server/router/api/v1/users/_userID/router.test.ts, src/server/router/api/v1/users/_userID/router.ts
=> Return a users most recently used imports on an endpoint.

src/lib/score-import/import-types/ir/usc/converter.ts, src/server/router/ir/usc/_playtype/router.ts
=> Remove code for USC ASR.

src/lib/search/search.ts, src/server/router/api/v1/search/router.test.ts, src/server/router/api/v1/search/router.ts, src/test-utils/mock-db/charts-bms.json
=> Support searching on BMS/PMS chart hashes

package.json, pnpm-lock.yaml, src/lib/constants/classes.ts, src/lib/score-import/framework/goals/goals.test.ts, src/lib/score-import/framework/goals/goals.ts, src/lib/score-import/import-types/common/batch-manual/parser.test.ts, src/lib/score-import/import-types/common/batch-manual/parser.ts, src/test-utils/test-data.ts
I need this for WACCA stage up import. This seemed like the cleanest/easiest way to do it (as opposed to e.g. creating a separate API endpoint just for class updates).
=> add class import to batch-manual/direct-manual

package.json, src/lib/constants/version.ts, src/lib/database-seeds/repo.ts
Hotfix for database-sync to call from the correct repo if on master.
=> Patch database-sync (v2.1.5)

src/lib/score-import/import-types/common/api-kai/sdvx/converter.test.ts, src/lib/score-import/import-types/common/api-kai/sdvx/converter.ts
idk how to build or test this JS stuff but this looks like an easy fix?
=> Add Judgement data to SDVX Kai converter

package.json, pnpm-lock.yaml, src/external/mongo/schemas.ts, src/lib/achievables/goal-utils.ts, src/lib/achievables/goals.test.ts, src/lib/achievables/goals.ts, src/lib/database-seeds/repo.ts, src/lib/score-import/framework/common/score-utils.ts, src/lib/score-import/framework/goals/goals.test.ts, src/lib/score-import/framework/goals/goals.ts, src/lib/score-import/framework/milestones/milestones.test.ts, src/lib/score-import/framework/sessions/sessions.ts, src/server/middleware/auth.ts, src/server/router/api/v1/games/_game/_playtype/goals/router.ts, src/server/router/api/v1/games/_game/_playtype/router.ts, src/server/router/api/v1/import/router.ts, src/server/router/api/v1/users/_userID/games/_game/_playtype/goals/router.ts, src/server/router/api/v1/users/_userID/games/_game/_playtype/router.ts, src/server/router/api/v1/users/_userID/router.ts, src/test-utils/test-data.ts, src/utils/db.ts, src/utils/folder.ts, src/utils/misc.ts, src/utils/prudence.ts, src/utils/queries/summary.ts, src/utils/types.ts
This PR **DOES NOT** finish up goals/milestones, but instead adds the bulk of the work.
This is necessary because tachi-common has deviated sufficiently far from the iteration currently on develop, and develop needs to get based against this sooner rather than later.
=> Add support for setting and getting goals.
